//! Terraform Remote State Backend — models
//!
//! Compatible with Terraform HTTP backend protocol:
//! <https://developer.hashicorp.com/terraform/language/settings/backends/http>

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;

// ─── State record ────────────────────────────────────────────────────────────

/// A single Terraform state version stored in the backend.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct TerraformState {
    pub id: i64,
    pub project_id: i32,
    pub workspace: String,
    pub serial: i32,
    pub lineage: String,
    /// Raw (possibly gzip-compressed, possibly AES-256-GCM encrypted) bytes.
    #[serde(skip)]
    pub state_data: Vec<u8>,
    pub encrypted: bool,
    pub md5: String,
    pub created_at: DateTime<Utc>,
}

/// Summary row returned to the UI (no raw bytes).
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct TerraformStateSummary {
    pub id: i64,
    pub project_id: i32,
    pub workspace: String,
    pub serial: i32,
    pub lineage: String,
    pub encrypted: bool,
    pub md5: String,
    pub created_at: DateTime<Utc>,
}

// ─── Lock ────────────────────────────────────────────────────────────────────

/// Active lock held on a workspace.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct TerraformStateLock {
    pub project_id: i32,
    pub workspace: String,
    pub lock_id: String,
    pub operation: String,
    pub info: String,
    pub who: String,
    pub version: String,
    pub path: String,
    pub created_at: DateTime<Utc>,
    pub expires_at: DateTime<Utc>,
}

/// The JSON body Terraform sends in LOCK / UNLOCK requests.
/// Maps directly to the Terraform LockInfo struct.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct LockInfo {
    /// UUID generated by Terraform for this lock.
    #[serde(rename = "ID")]
    pub id: String,
    /// "OperationTypePlan", "OperationTypeApply", etc.
    pub operation: String,
    pub info: String,
    pub who: String,
    pub version: String,
    pub created: Option<String>,
    pub path: String,
}

impl LockInfo {
    pub fn from_lock(lock: &TerraformStateLock) -> Self {
        Self {
            id: lock.lock_id.clone(),
            operation: lock.operation.clone(),
            info: lock.info.clone(),
            who: lock.who.clone(),
            version: lock.version.clone(),
            created: Some(lock.created_at.to_rfc3339()),
            path: lock.path.clone(),
        }
    }
}

// ─── State diff ──────────────────────────────────────────────────────────────

/// Describes a resource change between two state versions.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StateDiffResource {
    pub address: String,
    pub change_type: String, // "added" | "changed" | "removed" | "unchanged"
    pub resource_type: String,
    pub name: String,
}

/// Result of diffing two state serials.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StateDiff {
    pub from_serial: i32,
    pub to_serial: i32,
    pub resources: Vec<StateDiffResource>,
    pub added: usize,
    pub changed: usize,
    pub removed: usize,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lock_info_from_lock() {
        let lock = TerraformStateLock {
            project_id: 1,
            workspace: "default".to_string(),
            lock_id: "abc-123".to_string(),
            operation: "OperationTypeApply".to_string(),
            info: "Apply operation".to_string(),
            who: "user@example.com".to_string(),
            version: "1.5.0".to_string(),
            path: "module.main".to_string(),
            created_at: Utc::now(),
            expires_at: Utc::now() + chrono::Duration::hours(1),
        };

        let info = LockInfo::from_lock(&lock);
        assert_eq!(info.id, "abc-123");
        assert_eq!(info.operation, "OperationTypeApply");
        assert_eq!(info.who, "user@example.com");
        assert_eq!(info.version, "1.5.0");
    }

    #[test]
    fn test_terraform_state_summary_serialization() {
        let summary = TerraformStateSummary {
            id: 1,
            project_id: 10,
            workspace: "prod".to_string(),
            serial: 5,
            lineage: "line-abc".to_string(),
            encrypted: true,
            md5: "d41d8cd98f00b204e9800998ecf8427e".to_string(),
            created_at: Utc::now(),
        };
        let json = serde_json::to_string(&summary).unwrap();
        assert!(json.contains("\"workspace\":\"prod\""));
        assert!(json.contains("\"serial\":5"));
        assert!(json.contains("\"encrypted\":true"));
        // state_data should be skipped
        assert!(!json.contains("state_data"));
    }

    #[test]
    fn test_state_diff_resource() {
        let resource = StateDiffResource {
            address: "aws_instance.web".to_string(),
            change_type: "added".to_string(),
            resource_type: "aws_instance".to_string(),
            name: "web".to_string(),
        };
        let json = serde_json::to_string(&resource).unwrap();
        assert!(json.contains("\"address\":\"aws_instance.web\""));
        assert!(json.contains("\"change_type\":\"added\""));
    }

    #[test]
    fn test_state_diff_serialization() {
        let diff = StateDiff {
            from_serial: 3,
            to_serial: 5,
            resources: vec![StateDiffResource {
                address: "aws_instance.web".to_string(),
                change_type: "added".to_string(),
                resource_type: "aws_instance".to_string(),
                name: "web".to_string(),
            }],
            added: 1,
            changed: 0,
            removed: 0,
        };
        let json = serde_json::to_string(&diff).unwrap();
        assert!(json.contains("\"from_serial\":3"));
        assert!(json.contains("\"to_serial\":5"));
        assert!(json.contains("\"added\":1"));
        assert!(json.contains("\"resources\":["));
    }

    #[test]
    fn test_state_diff_empty_resources() {
        let diff = StateDiff {
            from_serial: 1,
            to_serial: 2,
            resources: vec![],
            added: 0,
            changed: 0,
            removed: 0,
        };
        let json = serde_json::to_string(&diff).unwrap();
        assert!(json.contains("\"resources\":[]"));
    }

    #[test]
    fn test_lock_info_serialization() {
        let lock = TerraformStateLock {
            project_id: 1,
            workspace: "default".to_string(),
            lock_id: "lock-abc-123".to_string(),
            operation: "OperationTypePlan".to_string(),
            info: "Plan operation".to_string(),
            who: "user@example.com".to_string(),
            version: "1.5.0".to_string(),
            path: "module.main".to_string(),
            created_at: Utc::now(),
            expires_at: Utc::now() + chrono::Duration::hours(1),
        };
        let lock_info = LockInfo::from_lock(&lock);
        let json = serde_json::to_string(&lock_info).unwrap();
        // PascalCase serialization
        assert!(json.contains("\"ID\":\"lock-abc-123\""));
        assert!(json.contains("\"Operation\":\"OperationTypePlan\""));
    }

    #[test]
    fn test_terraform_state_lock_clone() {
        let lock = TerraformStateLock {
            project_id: 1,
            workspace: "prod".to_string(),
            lock_id: "clone-lock".to_string(),
            operation: "OperationTypeApply".to_string(),
            info: "Clone test".to_string(),
            who: "tester@example.com".to_string(),
            version: "1.5.0".to_string(),
            path: "module.main".to_string(),
            created_at: Utc::now(),
            expires_at: Utc::now(),
        };
        let cloned = lock.clone();
        assert_eq!(cloned.workspace, lock.workspace);
        assert_eq!(cloned.lock_id, lock.lock_id);
    }

    #[test]
    fn test_state_diff_resource_clone() {
        let resource = StateDiffResource {
            address: "aws_instance.web".to_string(),
            change_type: "changed".to_string(),
            resource_type: "aws_instance".to_string(),
            name: "web".to_string(),
        };
        let cloned = resource.clone();
        assert_eq!(cloned.address, resource.address);
        assert_eq!(cloned.change_type, resource.change_type);
    }

    #[test]
    fn test_terraform_state_summary_clone() {
        let summary = TerraformStateSummary {
            id: 1,
            project_id: 10,
            workspace: "prod".to_string(),
            serial: 5,
            lineage: "line-1".to_string(),
            encrypted: true,
            md5: "abc123".to_string(),
            created_at: Utc::now(),
        };
        let cloned = summary.clone();
        assert_eq!(cloned.workspace, summary.workspace);
        assert_eq!(cloned.serial, summary.serial);
    }

    #[test]
    fn test_terraform_state_summary_debug() {
        let summary = TerraformStateSummary {
            id: 1,
            project_id: 1,
            workspace: "debug".to_string(),
            serial: 1,
            lineage: "line-1".to_string(),
            encrypted: false,
            md5: "md5".to_string(),
            created_at: Utc::now(),
        };
        let debug_str = format!("{:?}", summary);
        assert!(debug_str.contains("TerraformStateSummary"));
    }

    #[test]
    fn test_terraform_state_lock_debug() {
        let lock = TerraformStateLock {
            project_id: 1,
            workspace: "debug-lock".to_string(),
            lock_id: "lock-123".to_string(),
            operation: "Plan".to_string(),
            info: "Debug info".to_string(),
            who: "debug@test.com".to_string(),
            version: "1.0".to_string(),
            path: "module.test".to_string(),
            created_at: Utc::now(),
            expires_at: Utc::now() + chrono::Duration::hours(1),
        };
        let debug_str = format!("{:?}", lock);
        assert!(debug_str.contains("TerraformStateLock"));
        assert!(debug_str.contains("debug-lock"));
    }

    #[test]
    fn test_lock_info_clone() {
        let lock = TerraformStateLock {
            project_id: 1,
            workspace: "clone-lock".to_string(),
            lock_id: "clone-id".to_string(),
            operation: "Apply".to_string(),
            info: "Clone info".to_string(),
            who: "clone@test.com".to_string(),
            version: "2.0".to_string(),
            path: "module.clone".to_string(),
            created_at: Utc::now(),
            expires_at: Utc::now(),
        };
        let info = LockInfo::from_lock(&lock);
        let cloned = info.clone();
        assert_eq!(cloned.id, info.id);
        assert_eq!(cloned.operation, info.operation);
    }

    #[test]
    fn test_state_diff_resource_all_change_types() {
        let change_types = ["added", "changed", "removed", "unchanged"];
        for ct in change_types {
            let resource = StateDiffResource {
                address: "res.addr".to_string(),
                change_type: ct.to_string(),
                resource_type: "aws_instance".to_string(),
                name: "test".to_string(),
            };
            let json = serde_json::to_string(&resource).unwrap();
            assert!(json.contains(&format!("\"change_type\":\"{}\"", ct)));
        }
    }

    #[test]
    fn test_state_diff_clone() {
        let diff = StateDiff {
            from_serial: 1,
            to_serial: 3,
            resources: vec![],
            added: 2,
            changed: 1,
            removed: 0,
        };
        let cloned = diff.clone();
        assert_eq!(cloned.from_serial, diff.from_serial);
        assert_eq!(cloned.added, diff.added);
    }

    #[test]
    fn test_terraform_state_summary_deserialization() {
        let json = r#"{"id":5,"project_id":20,"workspace":"staging","serial":10,"lineage":"line-5","encrypted":false,"md5":"xyz","created_at":"2024-01-01T00:00:00Z"}"#;
        let summary: TerraformStateSummary = serde_json::from_str(json).unwrap();
        assert_eq!(summary.workspace, "staging");
        assert_eq!(summary.serial, 10);
    }

    #[test]
    fn test_lock_info_with_optional_created() {
        let lock_info = LockInfo {
            id: "test-lock".to_string(),
            operation: "Test".to_string(),
            info: "Test info".to_string(),
            who: "test@test.com".to_string(),
            version: "1.0".to_string(),
            created: None,
            path: "module.test".to_string(),
        };
        let json = serde_json::to_string(&lock_info).unwrap();
        assert!(json.contains("\"ID\":\"test-lock\""));
        // created is None - may be skipped or null depending on serde config
        assert!(!json.contains("\"created\":\"2024")); // no actual date
    }
}
