---
# .github/workflows/community_release.yml
name: Community Release
# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v*-rc*"

permissions:
  contents: write

jobs:
  # 1. Сборка релизного пакета
  release:
    name: Сборка релиза
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v5

      - name: Установка Go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.23'  # Стабильная ветка

      - name: Установка Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'  # LTS-версия
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Установка go-task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Установка rpm
        run: sudo apt update && sudo apt-get install -y rpm

      - name: Установка зависимостей
        run: task deps

      - name: Импорт GPG ключа
        run: |
          echo "${{ secrets.GPG_KEY }}" | tr ' ' '\n' | base64 -d | \
            gpg --import --batch
          gpg --sign -u "${{ vars.GPG_KEY_ID }}" \
            --pinentry-mode loopback --yes --batch \
            --passphrase "${{ secrets.GPG_PASS }}" \
            --output unlock.sig --detach-sign README.md
          rm -f unlock.sig

      - name: Сброс состояния репозитория
        run: git reset --hard

      - name: Запуск релиза
        run: |
          GITHUB_TOKEN=${{ github.token }} \
          PROJECT_NAME=semaphore_community \
          GPG_KEY_ID="${{ vars.GPG_KEY_ID }}" \
            task release:prod

  # 2. Публикация Docker-образов
  deploy-prod:
    name: Публикация Community-образов
    runs-on: ubuntu-latest
    if: github.repository_owner == 'semaphoreui'
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v5

      - name: Настройка QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Настройка Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Авторизация в Docker Hub
        uses: docker/login-action@v4
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Метаданные Server
        id: server
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: velum/velum-community
          labels: |
            org.opencontainers.image.vendor=SemaphoreUI
            maintainer=Velum <support@semaphoreui.com>
          tags: type=raw,value=${{ github.ref_name }}
          flavor: latest=true

      - name: Сборка Server
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: deployment/docker/server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.server.outputs.labels }}
          tags: ${{ steps.server.outputs.tags }}

      - name: Сборка Server (Ansible 2.16.5)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: ANSIBLE_VERSION=9.4.0
          file: deployment/docker/server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.server.outputs.labels }}
          tags: >-
            velum/velum-community:${{ github.ref_name }}-ansible2.16.5

      - name: Сборка Server (PowerShell 7.5.0)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            POWERSHELL_VERSION=7.5.0
            SEMAPHORE_IMAGE=velum/velum-community
            SEMAPHORE_VERSION=${{ github.ref_name }}
          file: deployment/docker/server/powershell/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.server.outputs.labels }}
          tags: >-
            velum/velum-community:${{ github.ref_name }}-powershell7.5.0

      - name: Метаданные Runner
        id: runner
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: semaphoreui/runner-community
          labels: |
            org.opencontainers.image.vendor=SemaphoreUI
            maintainer=Velum <support@semaphoreui.com>
          tags: type=raw,value=${{ github.ref_name }}
          flavor: latest=true

      - name: Сборка Runner
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: deployment/docker/runner/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.runner.outputs.labels }}
          tags: ${{ steps.runner.outputs.tags }}

      - name: Сборка Runner (Ansible 2.16.5)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: ANSIBLE_VERSION=9.4.0
          file: deployment/docker/runner/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.runner.outputs.labels }}
          tags: >-
            semaphoreui/runner-community:${{ github.ref_name }}-ansible2.16.5

      - name: Сборка Runner (PowerShell 7.5.0)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            POWERSHELL_VERSION=7.5.0
            SEMAPHORE_IMAGE=semaphoreui/runner-community
            SEMAPHORE_VERSION=${{ github.ref_name }}
          file: deployment/docker/server/powershell/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.runner.outputs.labels }}
          tags: >-
            semaphoreui/runner-community:${{ github.ref_name }}-powershell7.5.0
