---
# .github/workflows/dev.yml
name: Dev Pipeline
on:  # yamllint disable-line rule:truthy
  push:
    branches: [develop, "2-*-stable"]
  pull_request:
    branches: [develop]

jobs:
  # 1. Локальная сборка и тесты
  build-local:
    name: Сборка и тесты (Local)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v5

      - name: Установка Go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.23'  # Стабильная ветка.
          # Замени на '^1.24', если используется nightly

      - name: Установка Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Установка go-task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Установка зависимостей
        run: task deps

      - name: Сборка проекта
        run: task build

      - name: Проверка неизменённых файлов
        run: |
          git diff --exit-code --stat -- . \
            ':(exclude)web/package.json' \
            ':(exclude)web/package-lock.json' \
            ':(exclude)go.mod' \
            ':(exclude)go.sum'

      - name: Запуск тестов
        run: task test

      - name: Сохранение бинарника
        uses: actions/upload-artifact@v5
        with:
          name: semaphore
          path: bin/semaphore
          retention-days: 1

  # 2. Миграции БД (BoltDB)
  migrate-boltdb:
    name: Миграция BoltDB
    needs: [build-local]
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка артефакта
        uses: actions/download-artifact@v8
        with:
          name: semaphore

      - name: Создание конфигурации
        run: |
          cat <<EOF > config.json
          {
            "bolt": {
              "host": "/tmp/database.bolt"
            },
            "dialect": "bolt",
            "email_alert": false
          }
          EOF

      - name: Применение миграций
        run: |
          chmod +x ./semaphore && ./semaphore migrate --config config.json

  # 3. Миграции БД (MySQL)
  migrate-mysql:
    name: Миграция MySQL
    needs: [build-local]
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: p455w0rd
          MYSQL_USER: semaphore
          MYSQL_PASSWORD: p455w0rd
          MYSQL_DATABASE: semaphore
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
    steps:
      - name: Загрузка артефакта
        uses: actions/download-artifact@v8
        with:
          name: semaphore

      - name: Создание конфигурации
        run: |
          cat <<EOF > config.json
          {
            "mysql": {
              "host": "localhost:3306",
              "user": "semaphore",
              "pass": "p455w0rd",
              "name": "semaphore"
            },
            "dialect": "mysql",
            "email_alert": false
          }
          EOF

      - name: Применение миграций
        run: |
          chmod +x ./semaphore && ./semaphore migrate --config config.json

  # 4. Миграции БД (MariaDB)
  migrate-mariadb:
    name: Миграция MariaDB
    needs: [build-local]
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.11
        env:
          MARIADB_ROOT_PASSWORD: p455w0rd
          MARIADB_USER: semaphore
          MARIADB_PASSWORD: p455w0rd
          MARIADB_DATABASE: semaphore
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
    steps:
      - name: Загрузка артефакта
        uses: actions/download-artifact@v8
        with:
          name: semaphore

      - name: Создание конфигурации
        run: |
          cat <<EOF > config.json
          {
            "mysql": {
              "host": "localhost:3306",
              "user": "semaphore",
              "pass": "p455w0rd",
              "name": "semaphore"
            },
            "dialect": "mysql",
            "email_alert": false
          }
          EOF

      - name: Применение миграций
        run: |
          chmod +x ./semaphore && ./semaphore migrate --config config.json

  # 5. Миграции БД (PostgreSQL)
  migrate-postgres:
    name: Миграция PostgreSQL
    needs: [build-local]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.22
        env:
          POSTGRES_USER: semaphore
          POSTGRES_PASSWORD: p455w0rd
          POSTGRES_DB: semaphore
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Загрузка артефакта
        uses: actions/download-artifact@v8
        with:
          name: semaphore

      - name: Создание конфигурации
        run: |
          cat <<EOF > config.json
          {
            "postgres": {
              "host": "localhost:5432",
              "user": "semaphore",
              "pass": "p455w0rd",
              "name": "semaphore",
              "options": {
                "sslmode": "disable"
              }
            },
            "dialect": "postgres",
            "email_alert": false
          }
          EOF

      - name: Применение миграций
        run: |
          chmod +x ./semaphore && ./semaphore migrate --config config.json

  # 6. Миграции БД (SQLite)
  migrate-sqlite:
    name: Миграция SQLite
    needs: [build-local]
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка артефакта
        uses: actions/download-artifact@v8
        with:
          name: semaphore

      - name: Создание конфигурации
        run: |
          cat <<EOF > config.json
          {
            "sqlite": {
              "host": "/tmp/db.sqlite"
            },
            "dialect": "sqlite",
            "email_alert": false
          }
          EOF

      - name: Применение миграций
        run: |
          chmod +x ./semaphore && ./semaphore migrate --config config.json

  # 7. Интеграционные тесты (BoltDB)
  integrate-boltdb:
    name: Интеграция BoltDB
    needs: [migrate-boltdb]
    runs-on: ubuntu-latest
    env:
      SEMAPHORE_DB_OPTIONS: '{"sessionConnection": "true"}'
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v5
      - name: Установка Go
        uses: actions/setup-go@v6
        with: {go-version: '^1.23'}
      - name: Установка Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Установка go-task
        run: go install github.com/go-task/task/v3/cmd/task@latest
      - name: Загрузка артефакта
        uses: actions/download-artifact@v8
        with: {name: semaphore}
      - name: Подготовка stdin для setup
        run: |
          cat <<EOF > config.stdin
          2
          /tmp/database.bolt
          /tmp/semaphore
          http://localhost:3000
          no
          no
          no
          no
          no
          no
          $(pwd)/.dredd
          admin
          admin@localhost
          Developer
          password
          EOF
      - name: Инициализация
        run: |
          chmod +x ./semaphore && ./semaphore setup - < config.stdin
      - name: Запуск Dredd-тестов
        run: |
          task dredd:goodman
          task dredd:deps
          task dredd:hooks
          task dredd:test

  # 8. Интеграционные тесты (MySQL)
  integrate-mysql:
    name: Интеграция MySQL
    needs: [migrate-mysql]
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: p455w0rd
          MYSQL_USER: semaphore
          MYSQL_PASSWORD: p455w0rd
          MYSQL_DATABASE: semaphore
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v5
      - name: Установка Go
        uses: actions/setup-go@v6
        with: {go-version: '^1.23'}
      - name: Установка Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Установка go-task
        run: go install github.com/go-task/task/v3/cmd/task@latest
      - name: Загрузка артефакта
        uses: actions/download-artifact@v8
        with: {name: semaphore}
      - name: Подготовка stdin для setup
        run: |
          cat <<EOF > config.stdin
          1
          localhost:3306
          semaphore
          p455w0rd
          semaphore
          /tmp/semaphore
          http://localhost:3000
          no
          no
          no
          no
          no
          no
          $(pwd)/.dredd
          admin
          admin@localhost
          Developer
          password
          EOF
      - name: Инициализация
        run: |
          chmod +x ./semaphore && ./semaphore setup - < config.stdin
      - name: Запуск Dredd-тестов
        run: |
          task dredd:goodman
          task dredd:deps
          task dredd:hooks
          task dredd:test

  # 9. Интеграционные тесты (MariaDB)
  integrate-mariadb:
    name: Интеграция MariaDB
    needs: [migrate-mariadb]
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.11
        env:
          MARIADB_ROOT_PASSWORD: p455w0rd
          MARIADB_USER: semaphore
          MARIADB_PASSWORD: p455w0rd
          MARIADB_DATABASE: semaphore
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v5
      - name: Установка Go
        uses: actions/setup-go@v6
        with: {go-version: '^1.23'}
      - name: Установка Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Установка go-task
        run: go install github.com/go-task/task/v3/cmd/task@latest
      - name: Загрузка артефакта
        uses: actions/download-artifact@v8
        with: {name: semaphore}
      - name: Подготовка stdin для setup
        run: |
          cat <<EOF > config.stdin
          1
          localhost:3306
          semaphore
          p455w0rd
          semaphore
          /tmp/semaphore
          http://localhost:3000
          no
          no
          no
          no
          no
          no
          $(pwd)/.dredd
          admin
          admin@localhost
          Developer
          password
          EOF
      - name: Инициализация
        run: |
          chmod +x ./semaphore && ./semaphore setup - < config.stdin
      - name: Запуск Dredd-тестов
        run: |
          task dredd:goodman
          task dredd:deps
          task dredd:hooks
          task dredd:test

  # 10. Интеграционные тесты (PostgreSQL)
  integrate-postgres:
    name: Интеграция PostgreSQL
    needs: [migrate-postgres]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.22
        env:
          POSTGRES_USER: semaphore
          POSTGRES_PASSWORD: p455w0rd
          POSTGRES_DB: semaphore
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v5
      - name: Установка Go
        uses: actions/setup-go@v6
        with: {go-version: '^1.23'}
      - name: Установка Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Установка go-task
        run: go install github.com/go-task/task/v3/cmd/task@latest
      - name: Загрузка артефакта
        uses: actions/download-artifact@v8
        with: {name: semaphore}
      - name: Подготовка stdin для setup
        run: |
          cat <<EOF > config.stdin
          3
          localhost:5432
          semaphore
          p455w0rd
          semaphore
          /tmp/semaphore
          http://localhost:3000
          no
          no
          no
          no
          no
          no
          $(pwd)/.dredd
          admin
          admin@localhost
          Developer
          password
          EOF
      - name: Инициализация
        run: |
          chmod +x ./semaphore && ./semaphore setup - < config.stdin
      - name: Запуск Dredd-тестов
        run: |
          task dredd:goodman
          task dredd:deps
          task dredd:hooks
          task dredd:test

  # 11. Интеграционные тесты (SQLite)
  integrate-sqlite:
    name: Интеграция SQLite
    needs: [migrate-sqlite]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v5
      - name: Установка Go
        uses: actions/setup-go@v6
        with: {go-version: '^1.23'}
      - name: Установка Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Установка go-task
        run: go install github.com/go-task/task/v3/cmd/task@latest
      - name: Загрузка артефакта
        uses: actions/download-artifact@v8
        with: {name: semaphore}
      - name: Подготовка stdin для setup
        run: |
          cat <<EOF > config.stdin
          4
          /tmp/database.sqlite
          /tmp/semaphore
          http://localhost:3000
          no
          no
          no
          no
          no
          no
          $(pwd)/.dredd
          admin
          admin@localhost
          Developer
          password
          EOF
      - name: Инициализация
        run: |
          chmod +x ./semaphore && ./semaphore setup - < config.stdin
      - name: Запуск Dredd-тестов
        run: |
          task dredd:goodman
          task dredd:deps
          task dredd:hooks
          task dredd:test

  # 12. Деплой Server (develop)
  deploy-server:
    name: Деплой Server (Develop)
    needs:
      - integrate-boltdb
      - integrate-mysql
      - integrate-mariadb
      - integrate-postgres
    runs-on: ubuntu-latest
    if: github.repository_owner == 'semaphoreui'
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v5
      - name: Настройка QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      - name: Настройка Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Авторизация в Docker Hub
        uses: docker/login-action@v4
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Метаданные Server
        id: server
        uses: docker/metadata-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: velum/velum-community
          labels: |
            org.opencontainers.image.vendor=SemaphoreUI
            maintainer=Velum <support@semaphoreui.com>
          tags: |
            type=raw,value=develop
          flavor: |
            latest=false
      - name: Сборка и публикация Server
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: deployment/docker/server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.server.outputs.labels }}
          tags: ${{ steps.server.outputs.tags }}

  # 13. Деплой Runner (develop)
  deploy-runner:
    name: Деплой Runner (Develop)
    needs:
      - integrate-boltdb
      - integrate-mysql
      - integrate-mariadb
      - integrate-postgres
    runs-on: ubuntu-latest
    if: github.repository_owner == 'semaphoreui'
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v5
      - name: Настройка QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      - name: Настройка Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Авторизация в Docker Hub
        uses: docker/login-action@v4
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Метаданные Runner
        id: runner
        uses: docker/metadata-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: semaphoreui/runner-community
          labels: |
            org.opencontainers.image.vendor=SemaphoreUI
            maintainer=Velum <support@semaphoreui.com>
          tags: |
            type=raw,value=develop
          flavor: |
            latest=false
      - name: Сборка и публикация Runner
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: deployment/docker/runner/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.runner.outputs.labels }}
          tags: ${{ steps.runner.outputs.tags }}
