---
# .github/workflows/pro_selfhosted_beta.yml
name: Pro Self-Hosted Release

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - v*-beta*
      - v*-rc*

permissions:
  contents: write

jobs:
  # Пререлизная сборка (Go + Node + Task)
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "^1.23"
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - name: Установка go-task
        run: >-
          go install
          github.com/go-task/task/v3/cmd/task@latest
      - name: Установка rpm
        run: sudo apt update && sudo apt-get install -y rpm
      # yamllint disable rule:line-length
      - name: Добавление PRO-модуля
        run: |
          REPO=https://${{ secrets.GH_TOKEN }}@github.com/velum/velumpro-module.git
          git clone "$REPO" pro_impl
          go work init . ./pro_impl
      # yamllint enable rule:line-length
      - name: Установка зависимостей
        run: task deps APP_BUILD_TYPE=pro_selfhosted
      # yamllint disable rule:line-length
      - name: Импорт GPG ключа
        run: |
          echo "${{ secrets.GPG_KEY }}" | tr " " "\n" | base64 -d | gpg --import --batch
          gpg --sign -u "${{ vars.GPG_KEY_ID }}" --pinentry-mode loopback --yes --batch --passphrase "${{ secrets.GPG_PASS }}" --output unlock.sig --detach-sign README.md
          rm -f unlock.sig
      # yamllint enable rule:line-length
      - name: Сброс состояния репозитория
        run: git reset --hard
      - name: Запуск релиза
        run: |
          APP_BUILD_TYPE=pro_selfhosted \
          GITHUB_TOKEN=${{ github.token }} \
          GPG_KEY_ID="${{ vars.GPG_KEY_ID }}" \
          PROJECT_NAME=semaphore \
            task release:prod

  # Сборка и публикация Docker-образов
  deploy-beta:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'semaphoreui'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Настройка QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      - name: Настройка Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Авторизация в ECR
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: public.ecr.aws
          username: ${{ vars.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1
      - name: Авторизация в Docker Hub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # --- Server ---
      - name: Server meta
        id: server
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            public.ecr.aws/semaphore/pro/server
            public.ecr.aws/semaphore/server
            velum/velum
          labels: |
            org.opencontainers.image.vendor=SemaphoreUI
            maintainer=Velum <support@semaphoreui.com>
          tags: type=raw,value=${{ github.ref_name }}

      - name: Server build
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            GH_TOKEN=${{ secrets.GH_TOKEN }}
            APP_BUILD_TYPE=pro_selfhosted
          file: deployment/docker/server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.server.outputs.labels }}
          tags: ${{ steps.server.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Server build (Ansible 2.16.5)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            ANSIBLE_VERSION=9.4.0
            GH_TOKEN=${{ secrets.GH_TOKEN }}
            APP_BUILD_TYPE=pro_selfhosted
          file: deployment/docker/server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.server.outputs.labels }}
          # yamllint disable rule:line-length
          tags: |
            public.ecr.aws/semaphore/pro/server:${{ github.ref_name }}-ansible2.16.5
            public.ecr.aws/semaphore/server:${{ github.ref_name }}-ansible2.16.5
            velum/velum:${{ github.ref_name }}-ansible2.16.5
          # yamllint enable rule:line-length
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Server build (PowerShell 7.5.0)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            POWERSHELL_VERSION=7.5.0
            SEMAPHORE_IMAGE=public.ecr.aws/semaphore/server
            SEMAPHORE_VERSION=${{ github.ref_name }}
            GH_TOKEN=${{ secrets.GH_TOKEN }}
            APP_BUILD_TYPE=pro_selfhosted
          file: deployment/docker/server/powershell/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.server.outputs.labels }}
          # yamllint disable rule:line-length
          tags: |
            public.ecr.aws/semaphore/pro/server:${{ github.ref_name }}-powershell7.5.0
            public.ecr.aws/semaphore/server:${{ github.ref_name }}-powershell7.5.0
            velum/velum:${{ github.ref_name }}-powershell7.5.0
          # yamllint enable rule:line-length
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      # --- Runner ---
      - name: Runner meta
        id: runner
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            public.ecr.aws/semaphore/pro/runner
            public.ecr.aws/semaphore/runner
            semaphoreui/runner
          labels: |
            org.opencontainers.image.vendor=SemaphoreUI
            maintainer=Velum <support@semaphoreui.com>
          tags: type=raw,value=${{ github.ref_name }}

      - name: Runner build
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            GH_TOKEN=${{ secrets.GH_TOKEN }}
          file: deployment/docker/runner/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.runner.outputs.labels }}
          tags: ${{ steps.runner.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Runner build (Ansible 2.16.5)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            ANSIBLE_VERSION=9.4.0
            GH_TOKEN=${{ secrets.GH_TOKEN }}
          file: deployment/docker/runner/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.runner.outputs.labels }}
          # yamllint disable rule:line-length
          tags: |
            public.ecr.aws/semaphore/pro/runner:${{ github.ref_name }}-ansible2.16.5
            public.ecr.aws/semaphore/runner:${{ github.ref_name }}-ansible2.16.5
            semaphoreui/runner:${{ github.ref_name }}-ansible2.16.5
          # yamllint enable rule:line-length
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Runner build (PowerShell 7.5.0)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            POWERSHELL_VERSION=7.5.0
            SEMAPHORE_IMAGE=public.ecr.aws/semaphore/runner
            SEMAPHORE_VERSION=${{ github.ref_name }}
            GH_TOKEN=${{ secrets.GH_TOKEN }}
          file: deployment/docker/server/powershell/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.runner.outputs.labels }}
          # yamllint disable rule:line-length
          tags: |
            public.ecr.aws/semaphore/pro/runner:${{ github.ref_name }}-powershell7.5.0
            public.ecr.aws/semaphore/runner:${{ github.ref_name }}-powershell7.5.0
            semaphoreui/runner:${{ github.ref_name }}-powershell7.5.0
          # yamllint enable rule:line-length
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
